# Generated by Django 5.0.7 on 2024-07-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'number']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tutor',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='staff_list.faculty'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='staff_list.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'building')},
        ),
    ]
