# Generated by Django 5.0.7 on 2024-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_list', '0005_tutor_created_tutor_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['surname', 'forenames']},
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='name',
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='forenames',
            field=models.CharField(default='xxx', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(default='xxx', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='surname',
            field=models.CharField(default='xxx', max_length=64),
            preserve_default=False,
        ),
    ]
